# Generated by Django 3.2.9 on 2021-11-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('products', '0004_alter_productlist_product_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='user',
        ),
        migrations.AddField(
            model_name='productlist',
            name='alert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alerts.productalert'),
            preserve_default=False,
        ),
    ]
