# Generated by Django 3.2.9 on 2021-11-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211120_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_json',
            field=models.JSONField(null=True),
        ),
    ]
