# Generated by Django 3.2.9 on 2021-11-20 11:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
