# Generated by Django 3.2.9 on 2021-11-22 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211120_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
